require:
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - lib/google/**/*

Naming/FileName:
  Exclude:
    - lib/protoc-plugin-rbs.rb
